### ISSUE TITLE
Error during execution of commands: `silently: not found`

### ISSUE THREAD

**Issue by planger** [eclipsesource/glsp-tutorial#21]
```
...
minimal-browser-app:  @ ./src-gen/frontend/index.js
minimal-browser-app: Done in 10.29s.
Done in 27.60s.

silently kill -9 $(lsof -t -i:3000)
Command failed: cd /home/philip/Temp/glsp-tutorial/glsp-tutorial && silently kill -9 $(lsof -t -i:3000)
/bin/sh: 1: silently: not found


silently kill -9 $(lsof -t -i:5013)
Command failed: cd /home/philip/Temp/glsp-tutorial/glsp-tutorial && silently kill -9 $(lsof -t -i:5013)
/bin/sh: 1: silently: not found


silently cd glsp-examples/minimal/client && yarn start:browser
Command failed: cd /home/philip/Temp/glsp-tutorial/glsp-tutorial && silently cd glsp-examples/minimal/client && yarn start:browser
/bin/sh: 1: silently: not found


All commands completed
```

**Comment by JonasHelming** [comment]
@planger Did you use tutorial maker extension version 0.4.0?

**Comment by max-elia** [comment]
The tutorial maker extension checks for `silently` **at the beginning** of a terminal command. Consecutive commands can be given as distict elements of an array and will be executed after the previous command has been finished (except for silently commands, which will fire the next command of the array after 1 sec, since they possibly don't terminate). Therefore the concatenated commands can be simply replaced with moving the `&& silently ...` to the next element of the array.
Also `yarn start:browser` should be run silently since it is starting a server and is not supposed to terminate and otherwise blocks the tutorial.

**Comment by planger** [comment]
> @planger Did you use tutorial maker extension version 0.4.0?

Hm, yes I'd think so. I was following the steps documented in the readme, which links to `0.3.0` for the manual installation method (not via OpenVSX). I can retest with `0.4.0` if that helps.

**Comment by JonasHelming** [comment]
Hmm, so it links to 0.3.0 but you installed 0.4.0?

**Comment by planger** [comment]
Sorry, that was misleading. :-/
I think I tested with 0.3.0 as I blindly followed the readme.

**Comment by JonasHelming** [comment]
The readme was pointing to a wrong version, I just updated that. Would you mind to retest only this issue with 0.4.0?
